from __future__ import annotations

"""
Onboarding documentation generator.

Assembles the architecture report, Mermaid diagrams, C4 model,
and LLM summaries into a complete Markdown onboarding document.
"""

from datetime import datetime
from typing import Dict, Optional

from src.architecture.analyzer import ArchitectureReport
from src.architecture.detector import ROLE_LABELS
from src.architecture.diagram import all_diagrams
from src.architecture.c4 import full_c4_model


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _mermaid_block(diagram_source: str, title: str = "") -> str:
    lines = []
    if title:
        lines.append(f"### {title}")
        lines.append("")
    lines.append("```mermaid")
    lines.append(diagram_source)
    lines.append("```")
    return "\n".join(lines)


def _code_block(content: str, lang: str = "text") -> str:
    return f"```{lang}\n{content}\n```"


def _section(title: str, level: int = 2) -> str:
    return "#" * level + " " + title


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_onboarding(
    report: ArchitectureReport,
    summaries: Optional[Dict[str, str]] = None,
    app_name: str = "",
) -> str:
    """
    Generate a complete Markdown onboarding document.

    Args:
        report    : ArchitectureReport from analyze()
        summaries : optional dict from summarizer.summarize_architecture()
        app_name  : optional application name override

    Returns:
        Complete Markdown string.
    """
    if not summaries:
        summaries = {}

    if not app_name:
        main_classes = report.roles_by_name.get("main", [])
        if main_classes:
            app_name = main_classes[0].class_name.replace("Application", "")
        else:
            app_name = (
                report.base_package.split(".")[-1].title()
                if report.base_package else "Application"
            )

    diagrams = all_diagrams(report)
    c4_doc = full_c4_model(report, app_name)

    sections = []

    # ---- Cover -------------------------------------------------------
    sections.append(f"# {app_name} -- Architecture Onboarding Guide")
    sections.append("")
    sections.append(
        f"> Auto-generated by RetroDecrypt Engine  "
        f"on {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    )
    sections.append("")
    sections.append("---")
    sections.append("")

    # ---- Table of Contents -------------------------------------------
    sections.append(_section("Table of Contents"))
    toc = [
        "1. [Project Overview](#1-project-overview)",
        "2. [Architecture Summary](#2-architecture-summary)",
        "3. [Package Structure](#3-package-structure)",
        "4. [Layered Architecture](#4-layered-architecture)",
        "5. [Key Components](#5-key-components)",
        "6. [Spring Boot Patterns](#6-spring-boot-patterns)",
        "7. [Module Boundaries](#7-module-boundaries)",
        "8. [Request Flow](#8-request-flow)",
        "9. [C4 Architecture Model](#9-c4-architecture-model)",
        "10. [Quick Start Guide](#10-quick-start-guide)",
        "11. [Architecture Diagrams](#11-architecture-diagrams)",
    ]
    if summaries.get("critique"):
        toc.append("12. [Architecture Review](#12-architecture-review)")
    sections.extend(toc)
    sections.append("")

    # ---- 1. Project Overview -----------------------------------------
    sections.append(_section("1. Project Overview"))
    sections.append("")
    intro = summaries.get(
        "onboarding_intro",
        (
            f"This is a Spring Boot application with "
            f"{report.stats.get('total_classes', 0)} Java classes "
            f"organized across {report.stats.get('layer_count', 0)} layers."
        ),
    )
    sections.append(intro)
    sections.append("")

    # Stats table
    sections.append("| Metric | Value |")
    sections.append("|--------|-------|")
    sections.append(f"| Base Package | `{report.base_package or 'unknown'}` |")
    sections.append(f"| Total Classes | {report.stats.get('total_classes', 0)} |")
    sections.append(f"| Architectural Layers | {report.stats.get('layer_count', 0)} |")
    sections.append(f"| Feature Modules | {len(report.modules)} |")
    sections.append(
        f"| Detection Rate | "
        f"{report.stats.get('detection_rate', 0)*100:.0f}% |"
    )
    if report.spring_patterns.entry_point_class:
        sections.append(
            f"| Entry Point | `{report.spring_patterns.entry_point_class}` |"
        )
    sections.append("")

    # ---- 2. Architecture Summary -------------------------------------
    sections.append(_section("2. Architecture Summary"))
    sections.append("")
    layer_summary = summaries.get("layer_summary", report.summary())
    sections.append(layer_summary)
    sections.append("")

    # ---- 3. Package Structure ----------------------------------------
    sections.append(_section("3. Package Structure"))
    sections.append("")
    sections.append(
        _mermaid_block(diagrams["package_diagram"], "Package Hierarchy")
    )
    sections.append("")

    # Package table
    sections.append("| Package | Role | Classes |")
    sections.append("|---------|------|---------|")
    pkg_map: Dict[str, list] = {}
    for cls in report.all_roles:
        pkg = cls.package or "(default)"
        pkg_map.setdefault(pkg, []).append(cls)

    for pkg in sorted(pkg_map.keys()):
        classes = pkg_map[pkg]
        dominant = max(
            set(c.role for c in classes),
            key=lambda r: sum(1 for c in classes if c.role == r)
        )
        label = ROLE_LABELS.get(dominant, dominant)
        sections.append(f"| `{pkg}` | {label} | {len(classes)} |")
    sections.append("")

    # ---- 4. Layered Architecture -------------------------------------
    sections.append(_section("4. Layered Architecture"))
    sections.append("")
    sections.append(
        _mermaid_block(diagrams["layer_diagram"], "Layer Overview")
    )
    sections.append("")

    for layer in report.layers:
        if layer.class_count == 0:
            continue
        sections.append(f"**{layer.name} Layer** ({layer.class_count} classes)")
        sections.append("")
        class_list = ", ".join(
            f"`{c.class_name}`" for c in layer.classes[:10]
        )
        if len(layer.classes) > 10:
            class_list += f" +{len(layer.classes) - 10} more"
        sections.append(f"Classes: {class_list}")
        sections.append("")

    # ---- 5. Key Components -------------------------------------------
    sections.append(_section("5. Key Components"))
    sections.append("")
    sections.append(
        _mermaid_block(diagrams["component_pie"], "Component Distribution")
    )
    sections.append("")

    sections.append("| Role | Classes | Count |")
    sections.append("|------|---------|-------|")
    for role, classes in sorted(
        report.roles_by_name.items(), key=lambda x: -len(x[1])
    ):
        if role == "unknown" or not classes:
            continue
        label = ROLE_LABELS.get(role, role)
        names = ", ".join(
            f"`{c.class_name}`" for c in sorted(classes, key=lambda c: c.class_name)[:5]
        )
        if len(classes) > 5:
            names += f" +{len(classes)-5} more"
        sections.append(f"| {label} | {names} | {len(classes)} |")
    sections.append("")

    # ---- 6. Spring Boot Patterns -------------------------------------
    sections.append(_section("6. Spring Boot Patterns"))
    sections.append("")
    spring_text = summaries.get(
        "spring_patterns",
        "\n".join(
            f"- {p}" for p in report.spring_patterns.patterns_detected
        ) or "No specific patterns detected.",
    )
    sections.append(spring_text)
    sections.append("")

    sp = report.spring_patterns
    sections.append("| Pattern | Detected | Count |")
    sections.append("|---------|----------|-------|")
    sections.append(f"| Spring Boot Main | {'Yes' if sp.has_spring_boot_main else 'No'} | - |")
    sections.append(f"| REST Controllers | Yes | {sp.rest_controller_count} |")
    sections.append(f"| JPA Entities | {'Yes' if sp.jpa_entity_count else 'No'} | {sp.jpa_entity_count} |")
    sections.append(f"| Spring Data Repos | {'Yes' if sp.spring_data_repo_count else 'No'} | {sp.spring_data_repo_count} |")
    sections.append(f"| Spring Security | {'Yes' if sp.has_security else 'No'} | - |")
    sections.append(f"| Scheduled Tasks | {'Yes' if sp.has_scheduling else 'No'} | - |")
    sections.append(f"| Async Processing | {'Yes' if sp.has_async else 'No'} | - |")
    sections.append("")

    # ---- 7. Module Boundaries ----------------------------------------
    sections.append(_section("7. Module Boundaries"))
    sections.append("")
    module_text = summaries.get("module_summary", "")
    if module_text:
        sections.append(module_text)
        sections.append("")

    if report.modules:
        sections.append("| Module | Root Package | Classes | Roles | Full-Stack |")
        sections.append("|--------|-------------|---------|-------|------------|")
        for mod in sorted(report.modules, key=lambda m: m.name):
            roles_str = ", ".join(sorted(mod.roles_present))
            sections.append(
                f"| {mod.name} | `{mod.root_package}` | "
                f"{len(mod.classes)} | {roles_str} | "
                f"{'Yes' if mod.is_full_stack else 'No'} |"
            )
    else:
        sections.append(
            "_No feature modules detected. Package structure is role-based._"
        )
    sections.append("")

    # ---- 8. Request Flow ---------------------------------------------
    sections.append(_section("8. Request Flow"))
    sections.append("")
    sections.append(
        _mermaid_block(diagrams["request_flow"], "Typical HTTP Request Flow")
    )
    sections.append("")
    sections.append(
        _mermaid_block(diagrams["dependency_flow"], "Data Flow Through Layers")
    )
    sections.append("")

    # ---- 9. C4 Architecture Model ------------------------------------
    sections.append(_section("9. C4 Architecture Model"))
    sections.append("")
    sections.append(_code_block(c4_doc))
    sections.append("")

    # ---- 10. Quick Start Guide ---------------------------------------
    sections.append(_section("10. Quick Start Guide"))
    sections.append("")
    qs = summaries.get(
        "quick_start",
        "See the controller classes for API entry points, then trace through services and repositories.",
    )
    sections.append(qs)
    sections.append("")

    controllers = report.roles_by_name.get("controller", [])
    services    = report.roles_by_name.get("service", [])
    repos       = report.roles_by_name.get("repository", [])

    if controllers or services or repos:
        sections.append("**Reading order for new developers:**")
        sections.append("")
        step = 1
        if report.spring_patterns.entry_point_class:
            sections.append(
                f"{step}. Start with `{report.spring_patterns.entry_point_class}` "
                f"to understand application configuration"
            )
            step += 1
        if controllers:
            sections.append(
                f"{step}. Read `{controllers[0].class_name}` to understand the API surface"
            )
            step += 1
        if services:
            sections.append(
                f"{step}. Trace `{services[0].class_name}` for business logic"
            )
            step += 1
        if repos:
            sections.append(
                f"{step}. Review `{repos[0].class_name}` for data access patterns"
            )
        sections.append("")

    # ---- 11. Architecture Diagrams -----------------------------------
    sections.append(_section("11. Architecture Diagrams"))
    sections.append("")
    sections.append("> All diagrams are rendered by any Markdown viewer that supports Mermaid.")
    sections.append("")
    sections.append(
        _mermaid_block(diagrams["layer_diagram"], "Full Layer Architecture")
    )
    sections.append("")
    sections.append(
        _mermaid_block(diagrams["package_diagram"], "Package Hierarchy")
    )
    sections.append("")
    sections.append(
        _mermaid_block(diagrams["component_pie"], "Component Distribution")
    )
    sections.append("")

    # ---- 12. Architecture Review (optional) --------------------------
    if summaries.get("critique"):
        sections.append(_section("12. Architecture Review"))
        sections.append("")
        sections.append(summaries["critique"])
        sections.append("")

    sections.append("---")
    sections.append(
        f"_Generated by RetroDecrypt Engine -- "
        f"{datetime.now().strftime('%Y-%m-%d')}_"
    )

    return "\n".join(sections)
