"""
Documentation generator.

Produces a personalised .docx report in C:/temp with content that is
either LLM-generated (when an LLM instance is supplied) or falls back
to structured templates.

Framework detection
-------------------
The generator inspects the actual annotations and patterns extracted from
the codebase to decide whether it is dealing with:
  - Spring Boot  (has @SpringBootApplication / @RestController / Spring Data)
  - Spring       (uses some Spring annotations but not the full Boot stack)
  - Java         (plain Java application with no Spring)

Nothing is hard-coded as "Spring Boot".

LLM narrative
-------------
When an LLM is supplied, each major analytical section is generated by
the LLM using the actual analysis data as context.  Static python-docx
tables with concrete metrics are always included regardless.

Content depth by knowledge level
---------------------------------
  beginner     -- plain-language overview, components, getting-started, glossary
  intermediate -- architecture layers, patterns, component map, navigation guide
  advanced     -- dependency analysis, coupling interpretation, request flow, debt
  expert       -- full coupling metrics, C4 model, recommendations
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

try:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    _DOCX_AVAILABLE = True
except ImportError:
    _DOCX_AVAILABLE = False

from src.user_profile import UserProfile

OUTPUT_DIR = Path("C:/temp")
DATA_DIR   = Path(__file__).parent.parent / "data"

# Heading colours (R, G, B)
_CLR_DARK_BLUE = (31,  73,  125)
_CLR_MID_BLUE  = (68,  114, 196)
_CLR_TEAL      = (0,   112, 192)
_CLR_RED       = (192, 0,   0)
_CLR_ORANGE    = (230, 108, 0)
_CLR_GREEN     = (56,  142, 60)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def _load_json(path: Path) -> Optional[Any]:
    try:
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        pass
    return None


def _load_text(path: Path) -> str:
    try:
        if path.exists():
            return path.read_text(encoding="utf-8")
    except Exception:
        pass
    return ""


class _AnalysisData:
    """Container for all pre-computed analysis artefacts."""

    def __init__(self) -> None:
        self.metadata:      List[dict] = _load_json(DATA_DIR / "repository_metadata.json") or []
        self.arch_report:   dict       = _load_json(DATA_DIR / "architecture_report.json") or {}
        self.dep_analysis:  dict       = _load_json(DATA_DIR / "dependency_analysis.json") or {}
        self.dep_adjacency: dict       = _load_json(DATA_DIR / "dependency_adjacency.json") or {}
        self.c4_text:       str        = _load_text(DATA_DIR / "architecture_c4.txt")

    @property
    def available(self) -> bool:
        return bool(self.metadata or self.arch_report)

    @property
    def base_package(self) -> str:
        return self.arch_report.get("base_package", "")

    @property
    def total_files(self) -> int:
        return len(self.metadata)

    @property
    def total_classes(self) -> int:
        return self.arch_report.get("stats", {}).get("total_classes", 0)

    @property
    def layers(self) -> List[dict]:
        return [l for l in self.arch_report.get("layers", []) if l.get("class_count", 0) > 0]

    @property
    def modules(self) -> List[dict]:
        return self.arch_report.get("modules", [])

    @property
    def spring_patterns(self) -> dict:
        return self.arch_report.get("spring_patterns", {})

    @property
    def roles(self) -> dict:
        return self.arch_report.get("roles", {})

    @property
    def stats(self) -> dict:
        return self.arch_report.get("stats", {})

    @property
    def coupling_metrics(self) -> List[dict]:
        return self.dep_analysis.get("coupling_metrics", [])

    @property
    def circular_deps(self) -> List[dict]:
        return self.dep_analysis.get("circular_dependencies", [])

    @property
    def orphan_classes(self) -> List[str]:
        return self.dep_analysis.get("orphan_classes", [])

    @property
    def layer_violations(self) -> List[dict]:
        return self.dep_analysis.get("layer_violations", [])


# ---------------------------------------------------------------------------
# Framework detection  (never assumes Spring Boot)
# ---------------------------------------------------------------------------

_SPRING_ANNOTATIONS = frozenset({
    "SpringBootApplication", "EnableAutoConfiguration",
    "RestController", "RequestMapping", "GetMapping", "PostMapping",
    "PutMapping", "DeleteMapping", "PatchMapping",
    "Service", "Repository", "Component", "Configuration",
    "Autowired", "Inject", "Bean", "Transactional",
    "Entity", "Table", "MappedSuperclass",
    "EnableJpaRepositories", "EnableWebSecurity",
    "Scheduled", "Async", "EventListener",
})

_SPRING_IMPORT_PREFIXES = (
    "org.springframework.",
    "javax.persistence.",
    "jakarta.persistence.",
)


def detect_framework(data: _AnalysisData) -> str:
    """
    Determine the framework from detected annotations, patterns, and imports.
    Returns one of: 'Spring Boot', 'Spring', 'Java'
    """
    sp = data.spring_patterns

    # Definitive: @SpringBootApplication found
    if sp.get("has_spring_boot_main"):
        return "Spring Boot"

    # Two or more distinct Spring Boot features present
    boot_features = [
        sp.get("rest_controller_count", 0) > 0,
        sp.get("spring_data_repo_count", 0) > 0,
        sp.get("jpa_entity_count", 0) > 0,
        sp.get("has_security"),
        sp.get("has_scheduling"),
        sp.get("has_async"),
    ]
    if sum(bool(f) for f in boot_features) >= 2:
        return "Spring Boot"

    # Count Spring annotations and check imports across all files
    all_annotations: set = set()
    spring_import_found = False
    for fm in data.metadata:
        all_annotations.update(fm.get("annotations", []))
        for imp in fm.get("imports", []):
            if any(imp.startswith(p) for p in _SPRING_IMPORT_PREFIXES):
                spring_import_found = True

    spring_ann_count = len(all_annotations & _SPRING_ANNOTATIONS)
    core_boot = {"RestController", "SpringBootApplication", "EnableAutoConfiguration"}

    if spring_ann_count >= 3 or (spring_ann_count >= 1 and spring_import_found):
        return "Spring Boot" if (all_annotations & core_boot) else "Spring"
    if spring_import_found or spring_ann_count >= 1:
        return "Spring"

    return "Java"


# ---------------------------------------------------------------------------
# LLM context builder
# ---------------------------------------------------------------------------

def _build_llm_context(data: _AnalysisData, framework: str) -> str:
    """Build a compact, comprehensive text summary for the LLM prompt context."""
    sp    = data.spring_patterns
    stats = data.stats
    lines: List[str] = [
        "=== CODEBASE ANALYSIS DATA ===",
        f"Framework     : {framework}",
        f"Base Package  : {data.base_package or 'unknown'}",
        f"Source Files  : {data.total_files}",
        f"Total Classes : {data.total_classes}",
        f"Detected      : {stats.get('detected_classes', 0)} / {stats.get('total_classes', 0)}"
        f" ({stats.get('detection_rate', 0)*100:.0f}% classified)",
        f"Entry Point   : {sp.get('entry_point_class', 'not found')}",
        "",
    ]

    # Layers with class names
    if data.layers:
        lines.append("ARCHITECTURAL LAYERS:")
        for layer in data.layers:
            class_names: List[str] = []
            for role_key in layer.get("roles", []):
                class_names += [c["class_name"] for c in data.roles.get(role_key, [])[:6]]
            pkgs = ", ".join(sorted(set(layer.get("packages", []))))
            lines.append(
                f"  {layer['name']} ({layer['class_count']} classes): "
                f"{', '.join(class_names[:5])}"
                + (" ..." if len(class_names) > 5 else "")
            )
            if pkgs:
                lines.append(f"    packages: {pkgs}")
        lines.append("")

    # Classes by role with annotations
    if data.roles:
        lines.append("CLASSES BY ROLE:")
        for role_key, classes in sorted(data.roles.items(), key=lambda x: -len(x[1])):
            if not classes or role_key == "unknown":
                continue
            names = ", ".join(c["class_name"] for c in classes[:5])
            if len(classes) > 5:
                names += f" (+{len(classes)-5} more)"
            anns = list({a for c in classes for a in c.get("annotations", [])})[:4]
            lines.append(f"  {role_key}: {names}")
            if anns:
                lines.append(f"    annotations: {', '.join('@'+a for a in anns)}")
        lines.append("")

    # Framework patterns
    for pat in sp.get("patterns_detected", []):
        lines.append(f"  Pattern: {pat}")
    for k, v in {
        "REST Controllers": sp.get("rest_controller_count", 0),
        "JPA Entities": sp.get("jpa_entity_count", 0),
        "Spring Data Repos": sp.get("spring_data_repo_count", 0),
    }.items():
        if v:
            lines.append(f"  {k}: {v}")
    lines.append("")

    # Modules
    if data.modules:
        lines.append("FEATURE MODULES:")
        for m in data.modules:
            lines.append(
                f"  {m['name']}: {m.get('class_count',0)} classes "
                f"[{', '.join(m.get('roles',[]))}]"
                + (" [full-stack]" if m.get("is_full_stack") else "")
            )
        lines.append("")

    # Dependency analysis
    if data.coupling_metrics:
        lines.append("DEPENDENCY ANALYSIS:")
        lines.append(f"  Circular deps: {len(data.circular_deps)}")
        for cd in data.circular_deps:
            cycle = cd.get("cycle", [])
            lines.append(f"    Cycle: {' -> '.join(cycle + [cycle[0]])}")
        lines.append(f"  Orphans ({len(data.orphan_classes)}): {', '.join(data.orphan_classes[:5])}")
        lines.append(f"  Layer violations: {len(data.layer_violations)}")
        for v in data.layer_violations[:5]:
            lines.append(f"    {v.get('source')} -> {v.get('target')}")
        lines.append("")

        lines.append("COUPLING METRICS (Ca=afferent/in Ce=efferent/out I=instability):")
        top = sorted(data.coupling_metrics,
                     key=lambda m: -(m.get("Ca",0)+m.get("Ce",0)))[:12]
        for m in top:
            if m.get("Ca", 0) + m.get("Ce", 0) == 0:
                continue
            flag = " [HIGHLY COUPLED]" if m.get("highly_coupled") else ""
            lines.append(
                f"  {m['class_name']:<35} Ca={m['Ca']:>2} Ce={m['Ce']:>2} "
                f"I={m['instability']:.2f}{flag}"
            )
        lines.append("")

    # C4 excerpt
    if data.c4_text:
        lines.append("C4 MODEL (summary):")
        for line in data.c4_text.splitlines()[:25]:
            lines.append("  " + line)
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# LLM section prompts  (section key -> knowledge_level -> prompt template)
# ---------------------------------------------------------------------------

_SECTION_PROMPTS: Dict[str, Dict[str, str]] = {
    "overview": {
        "beginner": (
            "Write a 3-4 paragraph plain-language introduction to this {framework} application "
            "for a junior developer or new team member.\n"
            "Cover: (1) what the application does in business terms, (2) the main technical pieces "
            "and what each one is responsible for, (3) how they connect.\n"
            "Use simple language, explain jargon, reference actual class and package names."
        ),
        "intermediate": (
            "Write a 3-4 paragraph technical overview for a developer with intermediate Java experience.\n"
            "Cover: (1) purpose and scope of the application, (2) the architectural pattern, "
            "(3) main components and their responsibilities, (4) notable observations.\n"
            "Reference actual class names, packages, and layer names throughout."
        ),
        "advanced": (
            "Write a 4-5 paragraph in-depth overview for a senior developer or tech lead.\n"
            "Cover: (1) architectural style and how well it is applied, (2) the full component "
            "landscape with class names, (3) visible design decisions, (4) immediate structural "
            "concerns or strengths.\n"
            "Be analytical — interpret what the structure tells you about quality and maintainability."
        ),
        "expert": (
            "Write a 4-5 paragraph expert architectural overview for a principal engineer or architect.\n"
            "Evaluate: (1) architectural cohesion and separation of concerns, (2) adherence to "
            "layered / clean architecture principles, (3) the component landscape and any design patterns, "
            "(4) strategic risks or strengths.\n"
            "Cite actual class names and metrics. Provide insight beyond what the numbers alone reveal."
        ),
    },
    "architecture": {
        "intermediate": (
            "Analyse the {layer_count}-layer architecture for a developer with intermediate experience.\n"
            "For EACH layer: explain its role, name the classes in it, describe responsibilities "
            "and communication with adjacent layers.\n"
            "Conclude with an assessment of how well the layered pattern is applied. "
            "Write 4-6 paragraphs with actual class and package names."
        ),
        "advanced": (
            "Provide a deep architectural analysis for a tech lead.\n"
            "Analyse: (1) quality of layer separation, (2) dependency direction, "
            "(3) coupling between layers, (4) what the breakdown tells us about architectural discipline.\n"
            "Write 4-6 analytical paragraphs with class names, packages, and dependency data."
        ),
        "expert": (
            "Provide an expert architectural assessment of the layered structure and module organisation.\n"
            "Evaluate: (1) cohesion within each layer, (2) coupling across layer boundaries and change risk, "
            "(3) module boundary integrity, (4) adherence to SOLID at the architectural level, "
            "(5) architectural anti-patterns.\n"
            "Write 5-7 paragraphs with specific class and metric references."
        ),
    },
    "components": {
        "beginner": (
            "Describe the main component types for a new team member in plain language.\n"
            "For EACH role type (Controller, Service, Repository, etc.), write a short paragraph: "
            "what it does, why it exists, and give 1-2 real examples from the codebase.\n"
            "Assume the reader knows Java but is new to this architecture."
        ),
        "intermediate": (
            "Write a component responsibilities analysis for each detected role, "
            "targeted at an experienced developer.\n"
            "For each role: its purpose, what specific classes do, how it interacts with others, "
            "and observations about the design quality.\n"
            "Write 4-6 paragraphs with class names."
        ),
        "advanced": (
            "Write a detailed component design assessment for a tech lead.\n"
            "For the most important components: single responsibility adherence, injection patterns, "
            "interface usage, and design concerns visible from annotations and dependency data.\n"
            "Identify the 5-6 classes a developer MUST understand to work on this codebase. "
            "Write 4-6 analytical paragraphs."
        ),
        "expert": (
            "Write an expert component design assessment.\n"
            "Evaluate: (1) SOLID principle adherence at the component level, "
            "(2) injection strategy quality, (3) god classes or anemic patterns, "
            "(4) dependency injection design, (5) interface segregation.\n"
            "Write 5-7 paragraphs with class-level specifics."
        ),
    },
    "dependencies": {
        "advanced": (
            "Interpret the dependency analysis for a tech lead.\n"
            "Explain: (1) what the {cycle_count} circular dependenc(ies) mean in practice — "
            "real risk, severity, resolution approach; "
            "(2) what the coupling metrics reveal — which classes are most fragile; "
            "(3) what instability scores suggest about refactoring cost; "
            "(4) whether orphan classes are dead code or newly added.\n"
            "Write 4-6 analytical paragraphs. Be specific."
        ),
        "expert": (
            "Provide an expert dependency architecture analysis.\n"
            "Analyse: (1) each circular dependency cycle — root cause, impact on testability "
            "and deployment, recommended resolution pattern (interface extraction, events, etc.); "
            "(2) Ca/Ce ratios — identify the most architecturally fragile classes and explain why; "
            "(3) instability distribution — is the gradient pointing in the right direction? "
            "(4) layer violations — are they symptomatic of a deeper structural problem?\n"
            "Write 5-7 highly analytical paragraphs with class-level specifics."
        ),
    },
    "request_flow": {
        "advanced": (
            "Describe the request flow through this {framework} application for a tech lead, "
            "using actual class names.\n"
            "Trace a typical HTTP request from entry point through each layer to the data store "
            "and back. Identify key classes at each stage.\n"
            "Also: what happens at each hand-off, what transformations occur, any flow concerns.\n"
            "Write 3-4 paragraphs."
        ),
        "expert": (
            "Provide an expert request flow and transaction boundary analysis.\n"
            "Trace the full lifecycle: HTTP ingress, validation, business logic, persistence, "
            "response construction. Identify transaction boundaries, potential N+1 risks, "
            "and data-flow concerns.\n"
            "Write 4-5 paragraphs with class-level specifics."
        ),
    },
    "debt": {
        "advanced": (
            "Write a technical debt assessment for a tech lead.\n"
            "Based on the dependency analysis and any code review findings, identify: "
            "(1) highest-priority items, (2) likely effort, (3) risk of NOT addressing them.\n"
            "Write 3-5 paragraphs. Be specific about which classes or areas are affected."
        ),
        "expert": (
            "Provide a comprehensive technical debt evaluation for an architect.\n"
            "Quantify: circular dependencies, coupling violations, layer architecture breaches, "
            "code review findings.\n"
            "For each debt category: root cause, downstream risk (maintainability, testability, "
            "deployability), remediation strategy, estimated effort.\n"
            "Write 5-7 paragraphs with a clear priority ordering."
        ),
    },
    "recommendations": {
        "expert": (
            "Provide prioritised strategic architectural recommendations for an architect.\n"
            "For each recommendation: (1) state the problem with class/metric references, "
            "(2) impact if unaddressed, (3) recommended solution pattern with a concrete example, "
            "(4) priority (Critical/High/Medium).\n"
            "Aim for 5-8 concrete, actionable recommendations grounded entirely in the "
            "data above. No generic Java advice."
        ),
    },
    "getting_started": {
        "beginner": (
            "Write a friendly getting-started guide for a new team member.\n"
            "Cover: (1) what to read first and why, (2) how to understand the request flow quickly, "
            "(3) the 3-4 most important classes to understand, (4) tips for navigating the packages.\n"
            "Write 3-4 paragraphs in a practical, welcoming tone."
        ),
        "intermediate": (
            "Write a codebase navigation guide for a developer joining the team.\n"
            "Cover: (1) best entry points, (2) how packages map to business domains, "
            "(3) key classes every developer should know, (4) how to find code for a given feature.\n"
            "Write 3-4 practical paragraphs with class and package references."
        ),
    },
}


# ---------------------------------------------------------------------------
# LLM call helper
# ---------------------------------------------------------------------------

def _call_llm_section(
    llm: Any,
    profile: UserProfile,
    data: _AnalysisData,
    framework: str,
    section: str,
    context: str,
    label: str = "",
) -> str:
    """
    Call the LLM to generate narrative text for one document section.
    Returns generated text, or empty string on failure.
    """
    template = _SECTION_PROMPTS.get(section, {}).get(profile.knowledge_level, "")
    if not template:
        return ""

    instruction = template.format(
        framework=framework,
        layer_count=len(data.layers),
        cycle_count=len(data.circular_deps),
    )

    system = (
        f"You are a senior Java architect writing technical documentation.\n"
        f"Audience: {profile.role} | Java expertise: {profile.java_expertise}.\n"
        f"Purpose: {profile.purpose}. Depth: {profile.depth}.\n"
        f"Rules:\n"
        f"  1. Always cite actual class names and metrics from the analysis data provided.\n"
        f"  2. Be specific and analytical — interpret, not just describe.\n"
        f"  3. Do not invent facts not present in the data.\n"
        f"  4. Write flowing prose only. No markdown headings or bullet points.\n"
        f"  5. Separate logical paragraphs with a single blank line."
    )

    try:
        from langchain_core.messages import SystemMessage, HumanMessage
        print(f"    [{label or section}] generating…", end="", flush=True)
        response = llm.invoke([
            SystemMessage(content=system),
            HumanMessage(content=f"{context}\n\nTask:\n{instruction}"),
        ])
        text = getattr(response, "content", "").strip()
        print(" done." if text else " (no content).")
        return text
    except Exception as exc:
        print(f" failed: {exc}")
        return ""


# ---------------------------------------------------------------------------
# python-docx helpers
# ---------------------------------------------------------------------------

def _set_run_colour(run: Any, rgb: tuple) -> None:
    run.font.color.rgb = RGBColor(*rgb)


def _heading(doc: Any, text: str, level: int = 1,
             colour: tuple = _CLR_DARK_BLUE) -> None:
    h = doc.add_heading(text, level=level)
    h.alignment = WD_ALIGN_PARAGRAPH.LEFT
    for run in h.runs:
        _set_run_colour(run, colour)


def _para(doc: Any, text: str, bold: bool = False, italic: bool = False,
          size: int = 11, colour: Optional[tuple] = None) -> None:
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold   = bold
    run.italic = italic
    run.font.size = Pt(size)
    if colour:
        _set_run_colour(run, colour)


def _write_llm_text(doc: Any, text: str) -> None:
    """Write LLM-generated prose to the document, respecting paragraph breaks."""
    for block in text.split("\n\n"):
        block = block.strip()
        if block:
            _para(doc, block)


def _bullet(doc: Any, text: str, level: int = 0) -> None:
    style = "List Bullet" if level == 0 else "List Bullet 2"
    doc.add_paragraph(style=style).add_run(text)


def _table(doc: Any, headers: List[str], rows: List[List[str]],
           style: str = "Light List Accent 1") -> None:
    if not rows:
        return
    try:
        tbl = doc.add_table(rows=1, cols=len(headers))
        tbl.style = style
    except KeyError:
        tbl = doc.add_table(rows=1, cols=len(headers))
    hdr_row = tbl.rows[0]
    for i, h in enumerate(headers):
        cell = hdr_row.cells[i]
        cell.text = h
        for run in cell.paragraphs[0].runs:
            run.bold = True
    for data_row in rows:
        row = tbl.add_row()
        for i, val in enumerate(data_row):
            row.cells[i].text = str(val) if val is not None else ""
    doc.add_paragraph()


def _page_break(doc: Any) -> None:
    doc.add_page_break()


# ---------------------------------------------------------------------------
# Title page
# ---------------------------------------------------------------------------

def _build_title_page(doc: Any, profile: UserProfile, data: _AnalysisData,
                      framework: str) -> None:
    doc.add_paragraph()
    doc.add_paragraph()

    sp      = data.spring_patterns
    app_name = (
        sp.get("entry_point_class", "").replace("Application", " Application").strip()
        or (data.base_package.split(".")[-1].replace("-", " ").title() + " Application"
            if data.base_package else "Java Application")
    )

    tp = doc.add_paragraph()
    tp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = tp.add_run(app_name)
    run.bold = True
    run.font.size = Pt(28)
    _set_run_colour(run, _CLR_DARK_BLUE)

    sp_para = doc.add_paragraph()
    sp_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = sp_para.add_run(f"{framework} — Analysis Report")
    run.font.size = Pt(16)
    _set_run_colour(run, _CLR_MID_BLUE)

    doc.add_paragraph()
    level_labels = {
        "beginner":     "Beginner Guide",
        "intermediate": "Technical Overview",
        "advanced":     "Technical Deep Dive",
        "expert":       "Expert Architectural Assessment",
    }
    lp = doc.add_paragraph()
    lp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = lp.add_run(level_labels.get(profile.knowledge_level, "Analysis Report"))
    run.font.size = Pt(14)
    run.italic    = True
    _set_run_colour(run, _CLR_TEAL)

    doc.add_paragraph()
    doc.add_paragraph()
    for label, value in [
        ("Prepared for", profile.name),
        ("Role",         profile.role),
        ("Purpose",      profile.purpose),
        ("Framework",    framework),
        ("Date",         datetime.now().strftime("%Y-%m-%d %H:%M")),
        ("Generated by", "RetroDecrypt Platform"),
    ]:
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r1 = p.add_run(f"{label}: ")
        r1.bold = True
        r1.font.size = Pt(11)
        r2 = p.add_run(value)
        r2.font.size = Pt(11)

    _page_break(doc)


# ---------------------------------------------------------------------------
# Static data tables (always rendered regardless of LLM)
# ---------------------------------------------------------------------------

def _static_overview_table(doc: Any, data: _AnalysisData, framework: str) -> None:
    sp    = data.spring_patterns
    stats = data.stats
    _table(doc, ["Metric", "Value"], [
        ["Framework",            framework],
        ["Base package",         data.base_package or "N/A"],
        ["Source files",         str(data.total_files)],
        ["Total classes",        str(data.total_classes)],
        ["Architectural layers", str(stats.get("layer_count", 0))],
        ["Feature modules",      str(stats.get("module_count", 0))],
        ["Detection rate",       f"{stats.get('detection_rate', 0)*100:.0f}%"],
        ["REST controllers",     str(sp.get("rest_controller_count", 0))],
        ["Spring Data repos",    str(sp.get("spring_data_repo_count", 0))],
        ["JPA entities",         str(sp.get("jpa_entity_count", 0))],
    ])


def _static_layers_table(doc: Any, data: _AnalysisData) -> None:
    if not data.layers:
        return
    _table(doc, ["Layer", "Classes", "Packages", "Inbound", "Outbound"], [
        [
            l["name"], str(l["class_count"]),
            ", ".join(sorted(set(l.get("packages", [])))[:2]),
            str(l.get("inbound_deps", 0)),
            str(l.get("outbound_deps", 0)),
        ]
        for l in data.layers
    ])


def _static_components_table(doc: Any, data: _AnalysisData) -> None:
    role_labels = {
        "controller": "Controllers", "service": "Services",
        "repository": "Repositories", "entity": "Entities",
        "dto": "DTOs", "configuration": "Configuration",
        "component": "Components", "utility": "Utilities",
        "security": "Security", "exception": "Exceptions",
        "main": "Entry Points",
    }
    rows = []
    for role_key, classes in sorted(data.roles.items(), key=lambda x: -len(x[1])):
        if not classes or role_key == "unknown":
            continue
        names = ", ".join(c["class_name"] for c in sorted(classes, key=lambda c: c["class_name"])[:4])
        if len(classes) > 4:
            names += f" +{len(classes)-4} more"
        rows.append([role_labels.get(role_key, role_key.title()), str(len(classes)), names])
    if rows:
        _table(doc, ["Role", "Count", "Classes"], rows)


def _static_patterns_table(doc: Any, data: _AnalysisData) -> None:
    sp = data.spring_patterns
    if not sp:
        return
    _table(doc, ["Feature", "Detected", "Detail"], [
        ["Spring Boot Main",     "Yes" if sp.get("has_spring_boot_main") else "No", sp.get("entry_point_class") or "-"],
        ["REST Controllers",     "Yes" if sp.get("rest_controller_count") else "No", str(sp.get("rest_controller_count", 0))],
        ["JPA Entities",         "Yes" if sp.get("jpa_entity_count") else "No",      str(sp.get("jpa_entity_count", 0))],
        ["Spring Data Repos",    "Yes" if sp.get("spring_data_repo_count") else "No", str(sp.get("spring_data_repo_count", 0))],
        ["Spring Security",      "Yes" if sp.get("has_security") else "No", "-"],
        ["Scheduled Tasks",      "Yes" if sp.get("has_scheduling") else "No", "-"],
        ["Async Processing",     "Yes" if sp.get("has_async") else "No", "-"],
    ])


def _static_dependency_tables(doc: Any, data: _AnalysisData) -> None:
    _table(doc, ["Metric", "Value"], [
        ["Total classes in graph",  str(len(data.coupling_metrics))],
        ["Circular dependencies",   str(len(data.circular_deps))],
        ["Orphan classes",          str(len(data.orphan_classes))],
        ["Layer violations",        str(len(data.layer_violations))],
    ])
    if data.circular_deps:
        _heading(doc, "Circular Dependency Cycles", level=2, colour=_CLR_ORANGE)
        for cd in data.circular_deps:
            cycle = cd.get("cycle", [])
            _bullet(doc, " → ".join(cycle + [cycle[0]]))
    if data.orphan_classes:
        _heading(doc, "Orphan Classes", level=2, colour=_CLR_MID_BLUE)
        for cls in data.orphan_classes:
            _bullet(doc, cls)


def _static_coupling_table(doc: Any, data: _AnalysisData) -> None:
    if not data.coupling_metrics:
        return
    top = sorted(data.coupling_metrics, key=lambda m: -(m.get("Ca", 0) + m.get("Ce", 0)))[:15]
    _table(doc, ["Class", "Ca (in)", "Ce (out)", "Instability", "Highly Coupled"], [
        [
            m["class_name"], str(m["Ca"]), str(m["Ce"]),
            f"{m['instability']:.2f}",
            "⚠ Yes" if m.get("highly_coupled") else "No",
        ]
        for m in top if m.get("Ca", 0) + m.get("Ce", 0) > 0
    ])


def _static_glossary_table(doc: Any) -> None:
    _table(doc, ["Term", "Definition"], [
        ["Spring Boot",   "A framework for building Java web applications with minimal configuration."],
        ["Spring",        "A popular Java framework providing dependency injection, MVC, data access, and more."],
        ["REST API",      "Communication over HTTP using standard verbs (GET, POST, PUT, DELETE)."],
        ["Controller",    "Receives HTTP requests and delegates to the service layer."],
        ["Service",       "Contains the business logic and orchestrates operations."],
        ["Repository",    "Handles reading from and writing to the database."],
        ["Entity",        "A Java class that maps to a database table (via JPA/Hibernate)."],
        ["DTO",           "Data Transfer Object — carries data between layers without business logic."],
        ["Dependency",    "When one class uses another class."],
        ["Package",       "A namespace grouping related Java source files."],
        ["Annotation",    "A label starting with @ that gives the framework instructions about a class."],
        ["Coupling",      "How much one class depends on others. Lower coupling = easier to change."],
        ["Ca (afferent)", "How many classes depend ON this class. High Ca = widely used, risky to change."],
        ["Ce (efferent)", "How many classes this class depends ON. High Ce = may be fragile."],
        ["Instability I", "Ce / (Ca+Ce). 0 = fully stable. 1 = fully unstable."],
    ])


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _sec_overview(doc: Any, profile: UserProfile, data: _AnalysisData,
                  framework: str, llm: Any, ctx: str) -> None:
    _heading(doc, "1. Application Overview", level=1)
    text = _call_llm_section(llm, profile, data, framework, "overview", ctx, "Overview") if llm else ""
    if text:
        _write_llm_text(doc, text)
    else:
        _para(doc,
              f"This is a {framework} application"
              + (f" with base package '{data.base_package}'" if data.base_package else "")
              + f" comprising {data.total_files} source file(s) and {data.total_classes} "
              f"class(es) across {len(data.layers)} architectural layer(s).")
    doc.add_paragraph()
    _heading(doc, "Key Metrics", level=2, colour=_CLR_MID_BLUE)
    _static_overview_table(doc, data, framework)


def _sec_architecture(doc: Any, profile: UserProfile, data: _AnalysisData,
                       framework: str, llm: Any, ctx: str) -> None:
    _heading(doc, "2. Architecture Analysis", level=1)
    text = _call_llm_section(llm, profile, data, framework, "architecture", ctx, "Architecture") if llm else ""
    if text:
        _write_llm_text(doc, text)
    else:
        _para(doc, f"The application uses a {len(data.layers)}-layer architecture.")
    if data.layers:
        doc.add_paragraph()
        _heading(doc, "Layer Summary", level=2, colour=_CLR_MID_BLUE)
        _static_layers_table(doc, data)


def _sec_components(doc: Any, profile: UserProfile, data: _AnalysisData,
                     framework: str, llm: Any, ctx: str) -> None:
    _heading(doc, "3. Key Components", level=1)
    text = _call_llm_section(llm, profile, data, framework, "components", ctx, "Components") if llm else ""
    if text:
        _write_llm_text(doc, text)
    else:
        _para(doc, "The following component roles are present in the codebase:")
    doc.add_paragraph()
    _heading(doc, "Component Roles", level=2, colour=_CLR_MID_BLUE)
    _static_components_table(doc, data)


def _sec_patterns(doc: Any, data: _AnalysisData) -> None:
    _heading(doc, "4. Framework Patterns", level=1)
    for pat in data.spring_patterns.get("patterns_detected", []):
        _bullet(doc, pat)
    doc.add_paragraph()
    _static_patterns_table(doc, data)


def _sec_modules(doc: Any, data: _AnalysisData) -> None:
    _heading(doc, "5. Feature Modules", level=1)
    if not data.modules:
        _para(doc, "Flat role-based package structure (no feature modules detected).", italic=True)
        return
    _para(doc, f"{len(data.modules)} module(s) group related classes under a common root package.")
    doc.add_paragraph()
    _table(doc, ["Module", "Root Package", "Classes", "Roles", "Full-Stack"], [
        [m["name"], m.get("root_package", ""), str(m.get("class_count", 0)),
         ", ".join(sorted(m.get("roles", []))), "Yes" if m.get("is_full_stack") else "No"]
        for m in data.modules
    ])


def _sec_dependencies(doc: Any, profile: UserProfile, data: _AnalysisData,
                       framework: str, llm: Any, ctx: str) -> None:
    _heading(doc, "6. Dependency Analysis", level=1)
    if not data.coupling_metrics:
        _para(doc, "Dependency data not available. Run build_dependency_graph.py first.", italic=True)
        return
    text = _call_llm_section(llm, profile, data, framework, "dependencies", ctx, "Dependencies") if llm else ""
    if text:
        _write_llm_text(doc, text)
    else:
        _para(doc, "The dependency graph reveals the following structure:")
    doc.add_paragraph()
    _heading(doc, "Dependency Summary", level=2, colour=_CLR_MID_BLUE)
    _static_dependency_tables(doc, data)


def _sec_coupling_metrics(doc: Any, data: _AnalysisData) -> None:
    _heading(doc, "7. Coupling Metrics", level=1)
    _para(doc,
          "Ca: how many classes depend ON this class — high Ca = stable but risky to change.\n"
          "Ce: how many classes this class depends ON — high Ce = depends on many others.\n"
          "Instability I = Ce / (Ca+Ce): 0 = fully stable, 1 = fully unstable.")
    doc.add_paragraph()
    _static_coupling_table(doc, data)


def _sec_request_flow(doc: Any, profile: UserProfile, data: _AnalysisData,
                       framework: str, llm: Any, ctx: str) -> None:
    _heading(doc, "8. Request Flow", level=1)
    text = _call_llm_section(llm, profile, data, framework, "request_flow", ctx, "Request Flow") if llm else ""
    if text:
        _write_llm_text(doc, text)
    else:
        _para(doc, "Typical flow: HTTP Client → Controller → Service → Repository → Database → (back up as response).")


def _sec_c4(doc: Any, data: _AnalysisData) -> None:
    _heading(doc, "9. C4 Architecture Model", level=1)
    if not data.c4_text:
        _para(doc, "C4 model not available. Run build_architecture.py first.", italic=True)
        return
    _para(doc, "The C4 model describes the system at System Context, Container, and Component levels.")
    doc.add_paragraph()
    for line in data.c4_text.splitlines():
        s = line.strip()
        if not s or s.startswith("==="):
            continue
        if "C4 Model --" in s:
            _heading(doc, s.replace("C4 Model -- ", ""), level=2, colour=_CLR_MID_BLUE)
        elif s.startswith("[") or ":" in s:
            _para(doc, s, bold=("System:" in s or "Container:" in s))
        else:
            _para(doc, s)


def _sec_debt(doc: Any, profile: UserProfile, data: _AnalysisData,
              framework: str, llm: Any, ctx: str) -> None:
    _heading(doc, "10. Technical Debt", level=1)
    review = _load_json(DATA_DIR / "code_review_report.json")
    if review:
        _para(doc, f"Quality score: {review.get('quality_score', 0):.1f}/100  "
                   f"(Grade: {review.get('grade', 'N/A')})", bold=True)
        doc.add_paragraph()
    text = _call_llm_section(llm, profile, data, framework, "debt", ctx, "Technical Debt") if llm else ""
    if text:
        _write_llm_text(doc, text)
    else:
        if data.circular_deps:
            _para(doc, f"⚠  {len(data.circular_deps)} circular dependency cycle(s).", colour=_CLR_ORANGE)
        if data.layer_violations:
            _para(doc, f"⚠  {len(data.layer_violations)} layer violation(s).", colour=_CLR_ORANGE)
    if review and review.get("category_summaries"):
        doc.add_paragraph()
        _heading(doc, "Findings by Category", level=2, colour=_CLR_MID_BLUE)
        _table(doc, ["Category", "Total", "Critical", "High", "Medium", "Low"], [
            [s["category"], str(s["total"]), str(s["critical"]),
             str(s["high"]), str(s["medium"]), str(s["low"])]
            for s in review["category_summaries"] if s["total"] > 0
        ])


def _sec_recommendations(doc: Any, profile: UserProfile, data: _AnalysisData,
                           framework: str, llm: Any, ctx: str) -> None:
    _heading(doc, "11. Strategic Recommendations", level=1)
    text = _call_llm_section(llm, profile, data, framework, "recommendations", ctx, "Recommendations") if llm else ""
    if text:
        _write_llm_text(doc, text)
    else:
        recs: List[str] = []
        if data.circular_deps:
            recs.append(f"Resolve {len(data.circular_deps)} circular cycle(s) — use interface extraction or events.")
        if data.layer_violations:
            recs.append(f"Fix {len(data.layer_violations)} layer violation(s) — add an abstraction layer.")
        if data.orphan_classes:
            recs.append(f"Review {len(data.orphan_classes)} orphan class(es) — remove dead code or add tests.")
        if not recs:
            recs.append("No critical structural concerns detected in available data.")
        for i, r in enumerate(recs, 1):
            _para(doc, f"{i}. {r}")
            doc.add_paragraph()


def _sec_getting_started(doc: Any, profile: UserProfile, data: _AnalysisData,
                           framework: str, llm: Any, ctx: str) -> None:
    _heading(doc, "Getting Started", level=1)
    text = _call_llm_section(llm, profile, data, framework, "getting_started", ctx, "Getting Started") if llm else ""
    if text:
        _write_llm_text(doc, text)
    else:
        for i, s in enumerate([
            "Install dependencies:  pip install -r requirements.txt",
            "Create a .env file with your LLM API key.",
            "Run  python run.py  and follow the prompts.",
        ], 1):
            _para(doc, f"{i}. {s}")


def _sec_glossary(doc: Any) -> None:
    _heading(doc, "Glossary", level=1)
    _para(doc, "Key terms used in this document and in the codebase:")
    doc.add_paragraph()
    _static_glossary_table(doc)


# ---------------------------------------------------------------------------
# Document builder dispatcher
# ---------------------------------------------------------------------------

def _build_doc(doc: Any, profile: UserProfile, data: _AnalysisData,
               framework: str, llm: Any) -> None:
    ctx   = _build_llm_context(data, framework) if llm else ""
    level = profile.knowledge_level

    _build_title_page(doc, profile, data, framework)

    if level == "beginner":
        _sec_overview(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_components(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_getting_started(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_glossary(doc)

    elif level == "intermediate":
        _sec_overview(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_architecture(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_patterns(doc, data)
        _page_break(doc)
        _sec_components(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_modules(doc, data)
        _page_break(doc)
        _sec_getting_started(doc, profile, data, framework, llm, ctx)

    elif level == "advanced":
        _sec_overview(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_architecture(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_patterns(doc, data)
        _page_break(doc)
        _sec_components(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_modules(doc, data)
        _page_break(doc)
        _sec_dependencies(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_request_flow(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_debt(doc, profile, data, framework, llm, ctx)

    else:  # expert
        _sec_overview(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_architecture(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_patterns(doc, data)
        _page_break(doc)
        _sec_components(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_modules(doc, data)
        _page_break(doc)
        _sec_dependencies(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_coupling_metrics(doc, data)
        _page_break(doc)
        _sec_request_flow(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_c4(doc, data)
        _page_break(doc)
        _sec_debt(doc, profile, data, framework, llm, ctx)
        _page_break(doc)
        _sec_recommendations(doc, profile, data, framework, llm, ctx)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_documentation(profile: UserProfile, llm: Any = None) -> Path:
    """
    Generate a tailored .docx analysis report.

    Parameters
    ----------
    profile : UserProfile
        Collected user profile with a computed knowledge_level.
    llm : optional
        A loaded LangChain LLM instance.  When supplied, each analytical
        section is generated by the LLM using the actual codebase analysis
        data as grounding context.  When None, structured template content
        is written instead.

    Returns
    -------
    Path
        Absolute path to the generated .docx file saved in C:/temp.

    Raises
    ------
    ImportError
        If python-docx is not installed.
    """
    if not _DOCX_AVAILABLE:
        raise ImportError("python-docx is not installed.  Run: pip install python-docx")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    data      = _AnalysisData()
    framework = detect_framework(data)
    doc       = Document()

    if llm:
        print(f"  Detected framework : {framework}")
        print("  LLM section generation (one LLM call per section)…")

    _build_doc(doc, profile, data, framework, llm)

    safe_name   = "".join(c if c.isalnum() or c in "_- " else "_" for c in profile.name).replace(" ", "_")
    timestamp   = datetime.now().strftime("%Y%m%d_%H%M%S")
    level_label = profile.knowledge_level.title()
    filename    = f"JavaIntelligence_{safe_name}_{level_label}_{timestamp}.docx"
    out_path    = OUTPUT_DIR / filename

    doc.save(str(out_path))
    return out_path
